import React from 'react';
import './BookPage.css';

export default class BookPage extends React.Component {
  render() {
  return (
    <React.Fragment>
      <p id="book-page" theme={this.props.theme}>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nulla enim, egestas vel mi eu, aliquam euismod diam. Nam venenatis tristique risus, et interdum sapien malesuada vitae. Sed eget congue risus. Nullam efficitur felis id aliquet iaculis. Aenean viverra finibus feugiat. Maecenas quis eros ante. Morbi vitae iaculis diam, vitae cursus mauris. Nullam eget dui vitae ex feugiat porttitor. Fusce tempor felis a urna mollis, a vestibulum nisl malesuada. Nam sed ex ac erat consectetur blandit. Maecenas posuere sed felis ac varius. Fusce aliquet ultricies nisi, id tempus est. Aenean quam ligula, tempor ut magna dignissim, semper congue elit. Aliquam fringilla ultricies dapibus. Suspendisse sagittis gravida urna.

        Proin auctor vestibulum quam eu porta. Aenean tristique facilisis sem, id tincidunt tellus convallis sed. Duis maximus dui at congue tincidunt. In accumsan sem ipsum, nec egestas arcu sodales non. In dignissim scelerisque eros, eu semper ligula tempor at. Sed ultricies dolor lorem, sit amet auctor elit dignissim eu. Cras nulla purus, lobortis semper malesuada et, elementum sed magna. Vivamus efficitur magna nec massa auctor, in suscipit mi tempor.

        Aenean vel feugiat enim. Sed ultrices, augue ac tincidunt suscipit, nibh nulla bibendum ipsum, sed vestibulum mi sapien vitae lectus. Vivamus lacinia neque malesuada metus hendrerit, vel tristique nisl ultricies. Sed a dolor eget nisl ultricies consequat. Pellentesque sit amet volutpat nisl. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum hendrerit nisi eu blandit dictum. Praesent iaculis id magna eget gravida. Duis in pharetra erat, eget scelerisque nibh. Duis sed dolor a nibh vehicula venenatis sed nec risus. Proin turpis risus, efficitur eu leo nec, consectetur pharetra arcu. Aenean sed suscipit orci, eu aliquam purus. Praesent mattis lectus vitae augue dapibus rhoncus. Proin in pulvinar ante. Donec nisi turpis, ullamcorper eget suscipit non, consectetur at augue. Ut a cursus erat.

        Proin mattis nunc et risus iaculis, nec varius dolor maximus. Phasellus non porta metus, in pretium ligula. Donec gravida ex a velit placerat bibendum. Mauris felis nisi, molestie quis dignissim non, sollicitudin eu nisi. Mauris sit amet felis nec est varius sagittis at eu risus. Phasellus massa leo, varius non elit vel, varius ornare elit. Etiam in quam vel nibh viverra mollis. Nunc interdum feugiat lacinia.

        Maecenas nec aliquam tellus, at tristique justo. Nullam et est quam. Nunc pharetra condimentum justo, vitae ullamcorper tortor rutrum nec. Etiam molestie libero vel ullamcorper sagittis. Maecenas tempus ac dui quis euismod. Morbi posuere viverra nibh et posuere. Etiam in metus lacinia, cursus tortor non, varius eros. Vestibulum id dolor lorem. In iaculis vulputate lectus, vitae pretium nunc scelerisque ac. Praesent dignissim tempus feugiat. Pellentesque et eros rutrum, porttitor quam sit amet, bibendum velit. Donec auctor, dolor eu feugiat tincidunt, ex dolor posuere nisi, pellentesque egestas tortor tortor ut quam. Nam lacus libero, accumsan a maximus ac, lobortis nec urna.

        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nulla enim, egestas vel mi eu, aliquam euismod diam. Nam venenatis tristique risus, et interdum sapien malesuada vitae. Sed eget congue risus. Nullam efficitur felis id aliquet iaculis. Aenean viverra finibus feugiat. Maecenas quis eros ante. Morbi vitae iaculis diam, vitae cursus mauris. Nullam eget dui vitae ex feugiat porttitor. Fusce tempor felis a urna mollis, a vestibulum nisl malesuada. Nam sed ex ac erat consectetur blandit. Maecenas posuere sed felis ac varius. Fusce aliquet ultricies nisi, id tempus est. Aenean quam ligula, tempor ut magna dignissim, semper congue elit. Aliquam fringilla ultricies dapibus. Suspendisse sagittis gravida urna.

        Proin auctor vestibulum quam eu porta. Aenean tristique facilisis sem, id tincidunt tellus convallis sed. Duis maximus dui at congue tincidunt. In accumsan sem ipsum, nec egestas arcu sodales non. In dignissim scelerisque eros, eu semper ligula tempor at. Sed ultricies dolor lorem, sit amet auctor elit dignissim eu. Cras nulla purus, lobortis semper malesuada et, elementum sed magna. Vivamus efficitur magna nec massa auctor, in suscipit mi tempor.

        Aenean vel feugiat enim. Sed ultrices, augue ac tincidunt suscipit, nibh nulla bibendum ipsum, sed vestibulum mi sapien vitae lectus. Vivamus lacinia neque malesuada metus hendrerit, vel tristique nisl ultricies. Sed a dolor eget nisl ultricies consequat. Pellentesque sit amet volutpat nisl. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum hendrerit nisi eu blandit dictum. Praesent iaculis id magna eget gravida. Duis in pharetra erat, eget scelerisque nibh. Duis sed dolor a nibh vehicula venenatis sed nec risus. Proin turpis risus, efficitur eu leo nec, consectetur pharetra arcu. Aenean sed suscipit orci, eu aliquam purus. Praesent mattis lectus vitae augue dapibus rhoncus. Proin in pulvinar ante. Donec nisi turpis, ullamcorper eget suscipit non, consectetur at augue. Ut a cursus erat.

        Proin mattis nunc et risus iaculis, nec varius dolor maximus. Phasellus non porta metus, in pretium ligula. Donec gravida ex a velit placerat bibendum. Mauris felis nisi, molestie quis dignissim non, sollicitudin eu nisi. Mauris sit amet felis nec est varius sagittis at eu risus. Phasellus massa leo, varius non elit vel, varius ornare elit. Etiam in quam vel nibh viverra mollis. Nunc interdum feugiat lacinia.

        Maecenas nec aliquam tellus, at tristique justo. Nullam et est quam. Nunc pharetra condimentum justo, vitae ullamcorper tortor rutrum nec. Etiam molestie libero vel ullamcorper sagittis. Maecenas tempus ac dui quis euismod. Morbi posuere viverra nibh et posuere. Etiam in metus lacinia, cursus tortor non, varius eros. Vestibulum id dolor lorem. In iaculis vulputate lectus, vitae pretium nunc scelerisque ac. Praesent dignissim tempus feugiat. Pellentesque et eros rutrum, porttitor quam sit amet, bibendum velit. Donec auctor, dolor eu feugiat tincidunt, ex dolor posuere nisi, pellentesque egestas tortor tortor ut quam. Nam lacus libero, accumsan a maximus ac, lobortis nec urna.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nulla enim, egestas vel mi eu, aliquam euismod diam. Nam venenatis tristique risus, et interdum sapien malesuada vitae. Sed eget congue risus. Nullam efficitur felis id aliquet iaculis. Aenean viverra finibus feugiat. Maecenas quis eros ante. Morbi vitae iaculis diam, vitae cursus mauris. Nullam eget dui vitae ex feugiat porttitor. Fusce tempor felis a urna mollis, a vestibulum nisl malesuada. Nam sed ex ac erat consectetur blandit. Maecenas posuere sed felis ac varius. Fusce aliquet ultricies nisi, id tempus est. Aenean quam ligula, tempor ut magna dignissim, semper congue elit. Aliquam fringilla ultricies dapibus. Suspendisse sagittis gravida urna.

        Proin auctor vestibulum quam eu porta. Aenean tristique facilisis sem, id tincidunt tellus convallis sed. Duis maximus dui at congue tincidunt. In accumsan sem ipsum, nec egestas arcu sodales non. In dignissim scelerisque eros, eu semper ligula tempor at. Sed ultricies dolor lorem, sit amet auctor elit dignissim eu. Cras nulla purus, lobortis semper malesuada et, elementum sed magna. Vivamus efficitur magna nec massa auctor, in suscipit mi tempor.

        Aenean vel feugiat enim. Sed ultrices, augue ac tincidunt suscipit, nibh nulla bibendum ipsum, sed vestibulum mi sapien vitae lectus. Vivamus lacinia neque malesuada metus hendrerit, vel tristique nisl ultricies. Sed a dolor eget nisl ultricies consequat. Pellentesque sit amet volutpat nisl. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum hendrerit nisi eu blandit dictum. Praesent iaculis id magna eget gravida. Duis in pharetra erat, eget scelerisque nibh. Duis sed dolor a nibh vehicula venenatis sed nec risus. Proin turpis risus, efficitur eu leo nec, consectetur pharetra arcu. Aenean sed suscipit orci, eu aliquam purus. Praesent mattis lectus vitae augue dapibus rhoncus. Proin in pulvinar ante. Donec nisi turpis, ullamcorper eget suscipit non, consectetur at augue. Ut a cursus erat.

        Proin mattis nunc et risus iaculis, nec varius dolor maximus. Phasellus non porta metus, in pretium ligula. Donec gravida ex a velit placerat bibendum. Mauris felis nisi, molestie quis dignissim non, sollicitudin eu nisi. Mauris sit amet felis nec est varius sagittis at eu risus. Phasellus massa leo, varius non elit vel, varius ornare elit. Etiam in quam vel nibh viverra mollis. Nunc interdum feugiat lacinia.

        Maecenas nec aliquam tellus, at tristique justo. Nullam et est quam. Nunc pharetra condimentum justo, vitae ullamcorper tortor rutrum nec. Etiam molestie libero vel ullamcorper sagittis. Maecenas tempus ac dui quis euismod. Morbi posuere viverra nibh et posuere. Etiam in metus lacinia, cursus tortor non, varius eros. Vestibulum id dolor lorem. In iaculis vulputate lectus, vitae pretium nunc scelerisque ac. Praesent dignissim tempus feugiat. Pellentesque et eros rutrum, porttitor quam sit amet, bibendum velit. Donec auctor, dolor eu feugiat tincidunt, ex dolor posuere nisi, pellentesque egestas tortor tortor ut quam. Nam lacus libero, accumsan a maximus ac, lobortis nec urna.
        </p>
        </React.Fragment>
  );
}
}

